services:
  db:
    image: pgvector/pgvector:pg16
    container_name: bridge_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
